name: Perses Migration CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref_name != 'main' }}

jobs:
  gofmt:
    name: "check code format"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: migration
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
      - name: check format
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l .
            exit 1
          fi
      - name: check go.mod
        run: |
          go mod tidy
          if [ -n "$(git diff --name-only)" ]; then
            echo "go.mod or go.sum is not tidy"
            git diff
            exit 1
          fi

  golangci:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: migration
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: migration
          args: --timeout 5m